### ISSUE TITLE
Sample code missing

### ISSUE THREAD

**Issue by rewhex** [queelag/fcm#1]
Hey! Thank you for your work with this well documented project, I've read the docs, but still struggling at few things, and will be very happy to see sample code, because it's not very clear about how to register, store FCM tokens and id's, and receive messages.

Thanks

**Comment by alchemicas** [comment]
Hi @rewhex , I will add an example project inside the repository which will show how to properly integrate it, also for electron.

Sorry for the late reply! 🙏

**Comment by alchemicas** [comment]
An example for Node.js is now available inside the repo:
[https://github.com/queelag/fcm/tree/main/examples/node](https://github.com/queelag/fcm/tree/main/examples/node)

I will add the electron one soon enough!

**Comment by alchemicas** [comment]
Here I am again, the Electron example is available too, it's a bit more code than what I'd like an example to have, maybe it deserves its own library like push-receiver, I'll think about it.

[https://github.com/queelag/fcm/tree/main/examples/electron](https://github.com/queelag/fcm/tree/main/examples/electron)

Let me know if these examples help you @rewhex and feel free to close the issue if these examples satisfy you!
