### ISSUE TITLE
Migration from push-receiver issue

### ISSUE THREAD

**Issue by javajuice1337** [queelag/fcm#5]
Hello, I have been trying to migrate from push-receiver to Aracna FCM, but can't seem to figure it out. With push-receiver, I register the listener with a senderId, however, I don't see how to use the senderId with Aracna FCM. Any help is appreciated! Thanks.

**Comment by alchemicas** [comment]
Hi @javajuice1337 , as you might've noticed by patching the push-receiver library, it's not possible to use the senderId to register to FCM anymore with the new Firebase APIs.

Let me know if you need further help, but I guess you're happy enough with your own version of push-receiver!
